version: '2.1'
services:
  app:
    build: "./app"
    ports:  
      - "4567:4567"
    volumes:
      - "./app/app:/app"
    links:
      - db
  db:
    build: './db'
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
  web:
    build: "./web"
    ports:
      - "8080:8080"
    volumes_from:
      - app
    depends_on:
      - app
    links:
      - app
