# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra', '~> 2.0', '>= 2.0.5'
gem 'mustermann', '~> 1.0', '>= 1.0.3'
gem 'rack', '~> 2.0', '>= 2.0.7'
gem 'rack-protection', '~> 2.0', '>= 2.0.5'
gem 'unicorn'
gem 'tilt', '2.0'

gem 'mysql2'
gem 'ruby-mysql'
gem 'sequel'
